(defpackage #:xinput-cffi
  (:use #:cl)
  (:export #:+error-device-not-connected+
           #:+xinput-devtype-gamepad+
           #:+xinput-devsubtype-gamepad+
           #:+xinput-caps-voice-supported+
           #:+xinput-gamepad-dpad-up+
           #:+xinput-gamepad-dpad-down+
           #:+xinput-gamepad-dpad-left+
           #:+xinput-gamepad-dpad-right+
           #:+xinput-gamepad-start+
           #:+xinput-gamepad-back+
           #:+xinput-gamepad-left-thumb+
           #:+xinput-gamepad-right-thumb+
           #:+xinput-gamepad-left-shoulder+
           #:+xinput-gamepad-right-shoulder+
           #:+xinput-gamepad-a+
           #:+xinput-gamepad-b+
           #:+xinput-gamepad-x+
           #:+xinput-gamepad-y+
           #:+xinput-gamepad-left-thumb-deadzone+
           #:+xinput-gamepad-right-thumb-deadzone+
           #:+xinput-gamepad-trigger-threshold+
           #:+xinput-flag-gamepad+
           #:xinput-gamepad
           #:buttons
           #:left-trigger
           #:right-trigger
           #:thumb-lx
           #:thumb-ly
           #:thumb-rx
           #:thumb-ry
           #:xinput-state
           #:packet-number
           #:gamepad
           #:xinput-vibration
           #:left-motor-speed
           #:right-motor-speed
           #:xinput-capabilities
           #:type
           #:sub-type
           #:flags
           #:vibration
           #:guid
           #:data1
           #:data2
           #:data3
           #:data4
           #:xinput-get-state
           #:xinput-set-state
           #:xinput-get-capabilities
           #:xinput-get-dsound-audio-device-guids
           #:test-vibrate
           #:stop-vibrate))
